### ISSUE TITLE
No paginate method on my Model class

### ISSUE THREAD

**Issue by simonexmachina** [edwardhotchkiss/mongoose-paginate#9]
I must be doing something wrong because I don't have a `.paginate()` method on my Models. The following test case demonstrates the problem:

``` javascript
var mongoose = require('mongoose')
  , paginate = require('mongoose-paginate');

var BlogSchema = new mongoose.Schema({
  id    : mongoose.Schema.ObjectId,
  title : String,
  entry : String,
  date  : Date
});

var BlogEntry = mongoose.model('BlogEntry', BlogSchema);
console.log(BlogEntry.paginate); //=> outputs undefined
```

**Comment by sothychan** [comment]
Came across this since I had a similar problem.

In most tutorials, it says MyModel.plugin(paginate) -- reference: https://github.com/expressjs/express-paginate and this project's guide, but I think that's a bit wrong.  Looking at Mongoose's documentation, I believe the fix is you call plugin on the 'mongoose.schema' object, not the 'mongoose.model' object.

To fix the OP's code to make it work, it needs to be:

BlogSchema.plugin(paginate)
Now, when you console.log(BlogEntry.paginate), it will be a function (no longer undefined).

I hope this helps someone.

**Comment by cravindra** [comment]
I had similar issues and I googled around to no avail (other similar issues listed below)

I console.logged mongoose-paginate and it turned out to be a function which accepted a schema. 
(I'm guessing mongoose.plugin(pfunc) calls pfunc with `this` as the argument.

I called it on my schema object and it works for me now.

mongoose-paginate:^5.0.0

```js
// Load required packages
var mongoose = require('mongoose');
var timestamps = require('mongoose-timestamp');
var mongoosePaginate = require('mongoose-paginate');

// Define our Question schema
var QuestionSchema = new mongoose.Schema({
    text: {type: String, unique: true, required: true},
    type: {type: String, required: true},
    options: [String]
});

//Add auto timestamping
QuestionSchema.plugin(timestamps);

//Add Pagination
mongoosePaginate(QuestionSchema);

// Export the Mongoose model
module.exports = mongoose.model('questions', QuestionSchema);
```
Node: v4.4.3

npm: 2.15.1

mongoose: ^4.4.12

**Comment by ekumahost** [comment]
no solutions work. its been years here no perfect result
